### PR TITLE
Firsts steps towards Humble ue5.1

### PR DESCRIPTION
**Pull request by tomkimsour**
Here I added the ```"-D__STDC_VERSION__='201112L'"``` while compiling with colcon and it seems to remove every error. Since I am using ubuntu 22 and ros humble I also changed the bash script so it fits my needs.

### CODE REVIEW

**Comment by yuokamoto** [comment]
Thanks you for you pr.

I'm using Ubuntu 20.04 and foxy. what I experienced are
- it works with packaged ue project
- it crash with editor. it seems seg fault happen when dds trys to use port and system_error causes seg fault.

@tetorea or me can test with humble later but it may take time to prepare Ubuntu 22.04. Do you experience crash in editor?

**Comment by tomkimsour** [comment]
> Thanks you for you pr.
> 
> I'm using Ubuntu 20.04 and foxy. what I experienced are
> - it works with packaged ue project
> - it crash with editor. it seems seg fault happen when dds trys to use port and system_error causes seg fault.
> 
> @tetorea or me can test with humble later but it may take time to prepare Ubuntu 22.04. Do you experience crash in editor?
> 
> 

I didn't try it yet in unreal but I will try tomorrow.

**Comment by tomkimsour** [comment]
it is acutally not compiling. I did a mistake, I'm getting errors on what seems to be testing/debugging libraries.

**Comment by yuokamoto** [comment]
Thank you. I think I'm close to fix foxy + UE5.1 issue. I'll move to test humble after that.

**Comment by yuokamoto** [comment]
I created branches
- rclUE branch UE5_devel_humble. Havne't tested fully but build pass and ROS2Examples levels works
- UE_tools branch humble. since I'm not sure same changes works in foxy, I created different branch.

Could you please try?

**Comment by tomkimsour** [comment]
> * rclUE branch UE5_devel_humble. Havne't tested fully but build pass and ROS2Examples levels works
Are you trying your plugins with the turtlebot3-UE repo ?
> * UE_tools branch humble. since I'm not sure same changes works in foxy, I created different branch.
I just tried running ```python3 build_and_install_ros2_base.py --ue_path /home/crossing/UnrealEngine --ue_proj_path /home/crossing/Documents/Unreal\ Projects/Cabane\ 5.1```

And I am getting an error with the script. It tries to remove the ros2_ws that hasn't been created yet.
```
Cleanup workspace
Traceback (most recent call last):
  File "/home/crossing/Documents/UE_tools_official/BuildROS2/build_and_install_ros2_base.py", line 109, in <module>
    build_ros2(
  File "/home/crossing/Documents/UE_tools_official/BuildROS2/build_and_install_ros2.py", line 45, in build_ros2
    shutil.rmtree(ros)
  File "/usr/lib/python3.10/shutil.py", line 714, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.10/shutil.py", line 712, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/crossing/Documents/UE_tools_official/BuildROS2/ros2_ws'
```

**Comment by tomkimsour** [comment]
regarding the compilation I am still getting the same error as in #15

**Comment by yuokamoto** [comment]
- add directory exists check

**Comment by james-yoo** [comment]
ROS2 humble on Ubuntu 20.04 is not official target platform according to [REP 2000](https://www.ros.org/reps/rep-2000.html). I would like to suggest following configuration regarding to rclUE:

- UE 5.1 + ROS2 Humble + Ubuntu 22.04
- UE 5.1 + ROS2 Foxy + Ubuntu 20.04

**Comment by tomkimsour** [comment]
> ROS2 humble on Ubuntu 20.04 is not official target platform according to [REP 2000](https://www.ros.org/reps/rep-2000.html). I would like to suggest following configuration regarding to rclUE:
> 
> - UE 5.1 + ROS2 Humble + Ubuntu 22.04
> - UE 5.1 + ROS2 Foxy + Ubuntu 20.04

Yes, this is already the configuration I have been using

**Pull request closed without merging**
